### ISSUE TITLE
[BUG] __init__() got an unexpected keyword argument 'allowed_methods'

### ISSUE THREAD

**Issue by MarcusForss** [iamkroot/trakt-scrobbler#145]
**Describe the bug**

After upgrading to 1.3.0 scrobbling is not working and I can't use the trakts command, trying any command like --restart, status or --help gives the same error message that's in the subject line. 

**Desktop (please complete the following information):**
 - OS and Version: Windows 21H1
 - Python Version: 3.7.4
 - Player and Version: VLC 3.0.16 Vetinari

**To Reproduce**

1. Upgrade from 1.2.1 to 1.3.0 
2. Try any trakts command like status, --help or restart. 
3. Error __init__() got an unexpected keyword argument 'allowed_methods' pops in notifications

**Log file**

<details><summary>Click to see log contents</summary> 
<p>

```<!--DO NOT REMOVE THE THREE BACKTICKS. Replace only the next line completely-->
TypeError: __init__() got an unexpected keyword argument 'allowed_methods'
2021-08-23 14:31:31,458 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2021-08-23 14:31:45,052 - ERROR - MainThread - __init__ - Unhandled exception
Traceback (most recent call last):
  File "c:\users\marcus\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\marcus\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Marcus\.local\bin\trakts.exe\__main__.py", line 4, in <module>
    from trakt_scrobbler.console import main
  File "C:\Users\Marcus\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\console.py", line 6, in <module>
    from trakt_scrobbler.commands.backlog import BacklogCommand
  File "C:\Users\Marcus\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\commands\backlog.py", line 2, in <module>
    from trakt_scrobbler.utils import pluralize
  File "C:\Users\Marcus\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\utils.py", line 38, in <module>
    sess = init_sess()
  File "C:\Users\Marcus\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\utils.py", line 28, in init_sess
    backoff_factor=1
TypeError: __init__() got an unexpected keyword argument 'allowed_methods'
2021-08-23 14:31:45,054 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
```
</p>
</details>

**Comment by iamkroot** [comment]
Hmm. Did you upgrade from v1.2.1? Using `pipx upgrade trakt-scobbler`?

**Comment by MarcusForss** [comment]
Yep, followed the instruction on the release page. 

1. trakts stop
2. pipx upgrade trakt-scrobbler
3. trakts start

**Comment by iamkroot** [comment]
Try running `pipx upgrade trakt-scobbler --pip-args="--upgrade-strategy eager"`

**Comment by MarcusForss** [comment]
> ←[?25lPackage is not installed. Expected to find C:\Users\Marcus\.local\pipx\venvs\trakt-scobbler, but it does not exist.
←[?25h

**Comment by iamkroot** [comment]
That's weird.
Yeah, just reinstall:
1. `pipx uninstall trakt-scrobbler` (this will probably fail)
2. `pipx install trakt-scrobbler`

This will solve the issue for you, but I guess the upgrade instructions are still going to be wrong.

**Comment by MarcusForss** [comment]
Uninstall command was successful and the installation process is very straightforward anyway, easy enough. 
Thank you for the help :)

**Comment by iamkroot** [comment]
Ok I finally figured out the proper reason for this error - I forgot to update the requirements :P

Thanks for reporting the issue :)
